// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.tuke.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import sk.tuke.domain.Report;
import sk.tuke.domain.ReportDataOnDemand;
import sk.tuke.domain.Users;
import sk.tuke.domain.UsersDataOnDemand;

privileged aspect ReportDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReportDataOnDemand: @Component;
    
    private Random ReportDataOnDemand.rnd = new SecureRandom();
    
    private List<Report> ReportDataOnDemand.data;
    
    @Autowired
    UsersDataOnDemand ReportDataOnDemand.usersDataOnDemand;
    
    public Report ReportDataOnDemand.getNewTransientReport(int index) {
        Report obj = new Report();
        setDescription(obj, index);
        setEndTime(obj, index);
        setStartTime(obj, index);
        setUsers(obj, index);
        return obj;
    }
    
    public void ReportDataOnDemand.setDescription(Report obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ReportDataOnDemand.setEndTime(Report obj, int index) {
        Date endTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndTime(endTime);
    }
    
    public void ReportDataOnDemand.setStartTime(Report obj, int index) {
        Date startTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartTime(startTime);
    }
    
    public void ReportDataOnDemand.setUsers(Report obj, int index) {
        Users users = usersDataOnDemand.getRandomUsers();
        obj.setUsers(users);
    }
    
    public Report ReportDataOnDemand.getSpecificReport(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Report obj = data.get(index);
        Long id = obj.getId();
        return Report.findReport(id);
    }
    
    public Report ReportDataOnDemand.getRandomReport() {
        init();
        Report obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Report.findReport(id);
    }
    
    public boolean ReportDataOnDemand.modifyReport(Report obj) {
        return false;
    }
    
    public void ReportDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Report.findReportEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Report' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Report>();
        for (int i = 0; i < 10; i++) {
            Report obj = getNewTransientReport(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
