// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.tuke.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import sk.tuke.domain.Users;
import sk.tuke.domain.UsersDataOnDemand;

privileged aspect UsersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsersDataOnDemand: @Component;
    
    private Random UsersDataOnDemand.rnd = new SecureRandom();
    
    private List<Users> UsersDataOnDemand.data;
    
    public Users UsersDataOnDemand.getNewTransientUsers(int index) {
        Users obj = new Users();
        setAddress(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setPhoneNumber(obj, index);
        return obj;
    }
    
    public void UsersDataOnDemand.setAddress(Users obj, int index) {
        String address = "address_" + index;
        if (address.length() > 60) {
            address = address.substring(0, 60);
        }
        obj.setAddress(address);
    }
    
    public void UsersDataOnDemand.setFirstName(Users obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UsersDataOnDemand.setLastName(Users obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UsersDataOnDemand.setPhoneNumber(Users obj, int index) {
        String phoneNumber = "phoneNumber_" + index;
        obj.setPhoneNumber(phoneNumber);
    }
    
    public Users UsersDataOnDemand.getSpecificUsers(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Users obj = data.get(index);
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public Users UsersDataOnDemand.getRandomUsers() {
        init();
        Users obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public boolean UsersDataOnDemand.modifyUsers(Users obj) {
        return false;
    }
    
    public void UsersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Users.findUsersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Users' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Users>();
        for (int i = 0; i < 10; i++) {
            Users obj = getNewTransientUsers(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
