// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.tuke.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sk.tuke.domain.UsersIntegrationTest;

privileged aspect UsersIntegrationTest_Roo_Configurable {
    
    declare @type: UsersIntegrationTest: @Configurable;
    
}
